### ISSUE TITLE
Multiple entries in AlterInstaller.json

### ISSUE THREAD

**Issue by pagrey** [chenxiaolong/AlterInstaller#7]
Are multiple packages supported in the AlterInstaller.json file? I've tried a few different formats and nothing seems to work. I can get each entry to work if I use a different json file each time I install an application. I don't mind swapping the file each time but it would be great if it was possible.

```
{
    "org.package.a": {
        "installer": "com.android.vending",
        "updateOwner": "com.looker.droidify"
    }
    "org.package.b": {
        "installer": "com.android.vending",
        "updateOwner": "com.looker.droidify"
    }
}
```

**Comment by t0b0z** [comment]
Yes, I use it for mutiple packages without any problem. Your issue in the json is just a small syntax error. You need to add a comma between the two package entries. Here’s how it should look:
{
    "org.package.a": {
        "installer": "com.android.vending",
        "updateOwner": "com.looker.droidify"
    },
    "org.package.b": {
        "installer": "com.android.vending",
        "updateOwner": "com.looker.droidify"
    }
}

**Comment by pagrey** [comment]
Thanks!
